version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/server/node_modules
    depends_on:
      - database
    command: node dist/main
  database:
    container_name: mariadb
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    image: mariadb:10.5.8
